name: bcon4
channels:
  - cmutel
  - conda-forge
  - defaults
dependencies:
  - bw2data == 4.0.DEV18
  - bw2calc >= 2.0.DEV13
  - jupyterlab
  - pip
  - pip:
    - bw2io @ git+https://github.com/mfastudillo/brightway2-io.git@main
